tower-seed: -1.0
starting-floor: 10.0
dense-reward: 1.0
lighting-type: 1.0
visual-theme: 1.0
agent-perspective: 1.0
allowed-rooms: 1.0
allowed-modules: 2.0
allowed-floors: 2.0
total-floors: 20.0
default-theme: 0.0
